#!/bin/sh

#
# 发布代码到 dev 环境
# 方法一
#   update_file
#   需要更新的文件，相对路径
# 方法二
#   git 获取当前已经提交的最近 commit 变更文件

myexp() {
    if [ $? -ne 0 ]; then
        echo "-Err"
        echo " \033[31m-Err\033[0m"
        exit $?
    fi
}

srcPath="/Users/ott002/git/payment-backend"
if [ ! "$1" ]; then
    echo "please build environment [dev] or [qa] or [all]"
    exit 1
fi
updateFile=""
if [ "$2" -a -f "$2" ]; then
    updateFile="$2"
fi

# deploy code to dst
make_file() {
    local _dstPath="$1"

    if [ -z "$updateFile" ]; then
        files=$(cd $srcPath; git diff --name-only HEAD^..HEAD)
    else
        files=$(cat $updateFile)
    fi

    for f in $files; do
        /usr/local/bin/php -l "${srcPath}/${f}" >/dev/null
        if [ $? -ne 0 ]; then
            echo "\033[41;37m-Err, syntax error\033[0m"
            exit 1
        fi

        echo "${f}\c"
        rsync -av "${srcPath}/${f}" "ubuntu@devops:$_dstPath/${f}" 2>&1 >/dev/null
        myexp
        echo " \033[32m+Ok\033[0m"
    done
}

case "$1" in
    dev)
        make_file "/var/www/html/payment_dev"
        ;;
    qa)
        make_file "/var/www/html/payment"
        ;;
    all)
        echo "--> dev <--"
        make_file "/var/www/html/payment_dev"
        echo

        echo "--> qa <--"
        make_file "/var/www/html/payment"
        ;;
    *)
        echo "\033[41;37m-Err, dstPath not exists\033[0m"
        exit 2
        ;;
esac

