#!/bin/sh

#
# 发布代码到 dev 环境
# 方法一
#   update_file
#   需要更新的文件，相对路径
# 方法二
#   git 获取当前已经提交的最近 commit 变更文件

if [ ! "$1" ]; then
    echo "please build environment [dev] or [qa]"
    exit 1
fi
if [ "$1" -a "qa" == "$1" ]; then 
    dstPath="/var/www/html/payment"	
else
    dstPath="/var/www/html/payment_dev"	
fi
srcPath="/Users/ott002/git/payment-backend"

myexp() {
    if [ $? -ne 0 ]; then
        echo "-Err"
        echo " \033[31m-Err\033[0m"
        exit $?
    fi
}

updateFile=""
if [ "$2" -a -f "$2" ]; then
    updateFile="$2"
fi

if [ -z "$updateFile" ]; then
    files=$(cd $srcPath; git diff --name-only HEAD^..HEAD)
else
    files=$(cat $updateFile)
fi

for f in $files; do
    echo "${f}\c"
    rsync -av "${srcPath}/${f}" "ubuntu@devops:$dstPath/${f}" 2>&1 >/dev/null
    myexp
    echo " \033[32m+Ok\033[0m"
done

