# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs

PATH=$PATH:$HOME/bin:$HOME/local/bin:$HOME/local/sbin:/usr/bin/:/usr/sbin:/sbin:/bin
PATH=$PATH:/home/libo/git/david/i_libo/env/tool/bash

export PATH
