# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific aliases and functions

alias la="ls -al --time-style=long-iso"
alias j="jobs"
alias ll="ls -lh --time-style=long-iso"
